import Head from "next/head";
import { useState } from "react";
import Navbar from "../components/Navbar.js";
import BackgroundImage from "../components/BackgroundImage.js";
import { ImageComponent } from "../components/ImageComponent.js";
import data from "/data/data.json";
import desktopImage from "/public/images/crew/background-crew-desktop.jpg";
import tabletImage from "/public/images/crew/background-crew-tablet.jpg";

export default function Crew() {
  const navBar = [
    { title: "Home", index: "00", destination: "/", isActive: false },
    {
      title: "Destination",
      index: "01",
      destination: "destination",
      isActive: false,
    },
    { title: "Crew", index: "02", destination: "crew", isActive: true },
    {
      title: "Technology",
      index: "03",
      destination: "technology",
      isActive: false,
    },
  ];

  const [activeDestination, setActiveDestination] = useState(0);

  return (
    <>
      <div className="z-10 fixed min-w-full min-h-screen h-full overflow-y-scroll">
        <Head>
          <title>Crew</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <header>
          <Navbar navBar={navBar} />
        </header>

        <main className="flex flex-col items-center ff-barlow-condensed not-italic text-center text-white p-6 xl:w-full xl:px-36 xl:pt-20">
          <p className="w-full mb-8 text-white tracking-xl text-center md:text-left md:mt-10 md:mb-14 md:text-xl xl:mb-0 xl:text-3.5xl leading-8">
            <span className="text-white-shadow-10 font-bold mr-4">02</span>MEET
            YOUR CREW
          </p>
          <div className="md:flex md:flex-col-reverse xl:flex-row-reverse xl:justify-between xl:w-full">
            <div className="w-full flex flex-col items-center md:fixed md:bottom-0 md:right-0 md:left-0 xl:relative xl:bottom-0 xl:w-1/2 xl:max-w-2xl">
              <div className="w-80 h-56 flex justify-center items-end border-b border-white-shadow md:border-0 md:h-full md:w-full">
                <ImageComponent
                  alt="destinationImage"
                  source={data.crew[activeDestination].images.png}
                  mobileWidth="226"
                  desktopWidth="445"
                  tabletWidth="459"
                  mobileHeight="223"
                  desktopHeight="712"
                  tabletHeight="532"
                />
              </div>
            </div>
            <div className="md:flex md:flex-col-reverse xl:w-1/2 xl:items-start">
              <div className="h-2.5 mt-8 mb-5 flex justify-center md:my-10 xl:mt-0 xl:mb-24 xl:h-4">
                <ul className="w-22 flex justify-between uppercase text-sm leading-4 tracking-xl xl:w-36">
                  {data.destinations.map((_item, index) => (
                    <li
                      key={index}
                      className={`${
                        activeDestination == index
                          ? "bg-white"
                          : "bg-white-shadow hover:bg-white-shadow-20"
                      } h-2.5 w-2.5 rounded-full cursor-pointer xl:h-4 xl:w-4`}
                      onClick={() => setActiveDestination(index)}
                    ></li>
                  ))}
                </ul>
              </div>
              <section className="w-full ff-bellefair xl:flex xl:flex-col xl:h-full xl:mt-36">
                <p className="text-white-shadow-20 text-lg uppercase mb-2 md:text-2xl leading-7 xl:text-start xl:text-3xl xl:leading-9">
                  {data.crew[activeDestination].role}
                </p>
                <div className="text-white text-2xl leading-7 uppercase mb-4 md:text-4.5xl xl:text-start xl:text-6xl xl:leading-tight xl:w-full xl:mb-7">
                  {data.crew[activeDestination].name}
                </div>
                <p className="w-80 ff-barlow text-base leading-6 text-purple md:w-143.25 xl:w-118 xl:text-left xl:text-lg xl:leading-8 xl:h-40 xl:mb-22">
                  {data.crew[activeDestination].bio}
                </p>
              </section>
            </div>
          </div>
        </main>
      </div>

      <BackgroundImage desktopImage={desktopImage} tabletImage={tabletImage} />
    </>
  );
}
