import Head from "next/head";
import Navbar from "../components/Navbar.js";
import BackgroundImage from "../components/BackgroundImage.js";
import desktopImage from "/public/images/home-desktop-bg.jpg";
import tabletImage from "/public/images/home-tablet-bg.jpg";

export default function Home() {
  const navBar = [
    { title: "Home", index: "00", destination: "/", isActive: true },
    {
      title: "Destination",
      index: "01",
      destination: "destination",
      isActive: false,
    },
    { title: "Crew", index: "02", destination: "crew", isActive: false },
    {
      title: "Technology",
      index: "03",
      destination: "technology",
      isActive: false,
    },
  ];
  return (
    <>
      <div className="z-10 fixed min-w-full min-h-screen h-full overflow-y-scroll">
        <Head>
          <title>Space Tourism Website</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <header>
          <Navbar navBar={navBar} />
        </header>

        <main className="flex flex-col items-center ff-barlow-condensed not-italic text-center text-base md:text-2xl px-6 md:px-40.5 mt-12 md:mt-28 xl:flex-row xl:justify-between xl:mt-64">
          <section className="flex flex-col items-center xl:w-118">
            <h1 className="text-purple leading-5 md:leading-6 tracking-xl mb-4 xl:w-full xl:text-left">
              SO, YOU WANT TO TRAVEL TO
            </h1>
            <h2 className="text-white text-7.5xl md:text-10.5xl leading-tight md:leading-none ff-bellefair font-light mb-4 md:mb-6 xl:w-full xl:text-left">
              SPACE
            </h2>
            <div className="ff-barlow text-center text-purple text-base leading-6 md:leading-7 xl:text-start xl:text-lg">
              Let’s face it; if you want to go to space, you might as well
              genuinely go to outer space and not hover kind of on the edge of
              it. Well sit back, and relax because we’ll give you a truly out of
              this world experience!
            </div>
          </section>
          <section className="mt-20 mb-10">
            <h3 className="bg-white h-37.5 w-37.5 hover:ring-11 md:w-60 md:h-60 rounded-full ff-bellefair tracking-widest text-xl md:text-3xl md:font-thin flex justify-center items-center xl:w-72 xl:h-72 xl:hover:ring-22 hover:ring-white-shadow">
              EXPLORE
            </h3>
          </section>
        </main>
      </div>

      <BackgroundImage desktopImage={desktopImage} tabletImage={tabletImage} />
    </>
  );
}
